/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_JNI */

#ifndef _Included_application_JNI
#define _Included_application_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     application_JNI
 * Method:    execute
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_application_JNI_execute
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
